# hugo.toml

# Basic configuration
baseURL = 'https://info.antisoftware.net'
languageCode = 'en-us'
title = 'The Church of GNU'
theme = "hugo-book"
paginate = 5


# Build options
buildDrafts = false
buildExpired = false
buildFuture = false

# Miscellaneous
enableGitInfo = true
disablePathToLower = false
disableKinds = ['taxonomy']
