# Theme of the book
BookTheme = "auto"

# Generate a table of contents on the right side (per page it can also be specified)
BookToC = true

# /static/logo.png then the path would be 'logo.png'
#BookLogo = 'logo.png'

# Specify section of content to render as menu
# docs is default, * for all
BookSection = 'docs'

# Repository link
BookRepo = 'https://github.com/anticorpware/anticorp-wiki'

# Edit this page feature (requires: BookRepo parameter)
BookEditPath = 'edit/main'

# The date format used
BookDateFormat = 'Jan 2, 2006'

BookCommitPath = 'commit'

# Search functionality
BookSearch = false

# Comments functionality
BookComments = false




